apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-app  # Corrected the label to match template labels
  template:
    metadata:
      labels:
        app: online-app
    spec:
      containers:
        - name: online-app  # Corrected container name
          image: 967432970863.dkr.ecr.us-east-1.amazonaws.com/online-exam:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: database-1.ckhxbf4wuzkc.us-east-1.rds.amazonaws.com
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: onlineexam
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key:  password
      imagePullSecrets:
        - name: regcred
        
---
apiVersion: v1
kind: Service
metadata:
  name: online-service
spec:
  selector:
    app: online-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 
  type: LoadBalancer
